### PR TITLE
Add EPDQ::Client

### PR DESCRIPTION
**Pull request by andypearson**
EPDQ configuration no longer relies on class variables, hooray!

### CODE REVIEW

**Comment by alkesh** [comment]
would it be better to have it so that you do:

``` ruby
client.request
```

instead of 

``` ruby
EPDQ::Request.new
```

or is that too big of a refactor?

**Comment by andypearson** [comment]
@alkesh I did that already! You can do it both ways (below is an example of they way you would like). I would make `Request` and `Response` classes private if I could, they are an implementation detail now :)

``` ruby
class ClientTest < Test::Unit::TestCase
  # ...snip...

  test "can create a request" do
    client = EPDQ::Client.new(
      pspid: "MYPSPID",
      sha_in: "MYSHAIN",
      sha_out: "MYSHAOUT"
    )

    EPDQ::Request.expects(:new).with(client, param: 1).returns(:result)
    assert_equal :result, client.request(param: 1)
  end

  test "can create a response" do
    client = EPDQ::Client.new(
      pspid: "MYPSPID",
      sha_in: "MYSHAIN",
      sha_out: "MYSHAOUT"
    )

    EPDQ::Response.expects(:new).with(client, "query_string").returns(:result)
    assert_equal :result, client.response("query_string")
  end
end
```

**Comment by alkesh** [comment]
neat – it's practically perfect :thumbsup:

**Comment by andypearson** [comment]
Merged!

**Pull request merged**
